// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Profile struct {
	ID     string `json:"id"`
	UserID string `json:"userId"`
	Hobby  string `json:"hobby"`
}

type ProfileInput struct {
	UserID string `json:"userId"`
	Hobby  string `json:"hobby"`
}
